[project]
authors = ["TheSkyentist <raphael.hviding@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "AdventOfCode"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
